
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Domain.Models
{

using System;
    using System.Collections.Generic;
    
public partial class alltailoring
{

    public int Id { get; set; }

    public string Tailheaderid { get; set; }

    public string Alltable { get; set; }



    public virtual tailorbocket tailorbocket { get; set; }

    public virtual tailordetaile tailordetaile { get; set; }

    public virtual tailorhand tailorhand { get; set; }

    public virtual tailorheader tailorheader { get; set; }

    public virtual tailorjabzor tailorjabzor { get; set; }

    public virtual tailorneck tailorneck { get; set; }

}

}
