
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Domain.Models
{

using System;
    using System.Collections.Generic;
    
public partial class cashier
{

    public int Id { get; set; }

    public string SystemName { get; set; }

    public string Systemserial { get; set; }

    public string Materialname { get; set; }

    public Nullable<System.Guid> Comid { get; set; }

    public string CSR { get; set; }

    public string PrivateKey { get; set; }

    public string PublicKey { get; set; }

    public string Secret { get; set; }

    public string OTP { get; set; }

    public Nullable<int> Mode { get; set; }

    public Nullable<bool> Isusesigne { get; set; }

    public Nullable<int> Signtype { get; set; }

}

}
