
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Domain.Models
{

using System;
    using System.Collections.Generic;
    
public partial class company
{

    public System.Guid CompanyID { get; set; }

    public string Name { get; set; }

    public string ENName { get; set; }

    public string Address { get; set; }

    public string PhoneNo { get; set; }

    public string Taxnumber { get; set; }

    public string CRN { get; set; }

    public string CompanyLogo { get; set; }

    public string Logoname { get; set; }

    public string LogoENName { get; set; }

    public byte[] AllowInventory { get; set; }

    public byte[] ShowInPOS { get; set; }

    public byte[] IsUseShift { get; set; }

    public byte[] Discuontcheck { get; set; }

    public string Printername { get; set; }

    public string Printertype { get; set; }

    public string Sysnametype { get; set; }

    public Nullable<bool> ISUSEPrinter { get; set; }

    public Nullable<bool> ISUSEResturant { get; set; }

    public Nullable<bool> ISUSElineproduction { get; set; }

    public string Systemlang { get; set; }

    public bool ISUsePhase2 { get; set; }

    public string StreetName { get; set; }

    public string BuildingNumber { get; set; }

    public string CitySubdivisionName { get; set; }

    public string CityName { get; set; }

    public string PostalZone { get; set; }

    public Nullable<double> VatPercent { get; set; }

    public Nullable<short> PricesWithVAT { get; set; }

    public Nullable<bool> Isusesigne { get; set; }

    public Nullable<int> Signtype { get; set; }

    public string Salestype { get; set; }

    public Nullable<bool> ISUSETailor { get; set; }

}

}
