

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Domain.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

using System.Data.Entity.Core.Objects;
using System.Linq;


public partial class EasyposEntities : DbContext
{
    public EasyposEntities()
        : base("name=EasyposEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<cashier> cashiers { get; set; }

    public virtual DbSet<category> categories { get; set; }

    public virtual DbSet<company> companies { get; set; }

    public virtual DbSet<expencestype> expencestypes { get; set; }

    public virtual DbSet<expens> expenses { get; set; }

    public virtual DbSet<item> items { get; set; }

    public virtual DbSet<itemsale> itemsales { get; set; }

    public virtual DbSet<order> orders { get; set; }

    public virtual DbSet<payment> payments { get; set; }

    public virtual DbSet<paymentout> paymentouts { get; set; }

    public virtual DbSet<price> prices { get; set; }

    public virtual DbSet<pricedetaile> pricedetailes { get; set; }

    public virtual DbSet<product> products { get; set; }

    public virtual DbSet<productitem> productitems { get; set; }

    public virtual DbSet<purchasedetaile> purchasedetailes { get; set; }

    public virtual DbSet<purchase> purchases { get; set; }

    public virtual DbSet<sale> sales { get; set; }

    public virtual DbSet<salesdetaile> salesdetailes { get; set; }

    public virtual DbSet<staff> staffs { get; set; }

    public virtual DbSet<thirdparty> thirdparties { get; set; }

    public virtual DbSet<transaction> transactions { get; set; }

    public virtual DbSet<unittype> unittypes { get; set; }

    public virtual DbSet<expensesview> expensesviews { get; set; }

    public virtual DbSet<voucher> vouchers { get; set; }

    public virtual DbSet<exceptionpro> exceptionproes { get; set; }

    public virtual DbSet<alltailoring> alltailorings { get; set; }

    public virtual DbSet<tailorbocket> tailorbockets { get; set; }

    public virtual DbSet<tailordetaile> tailordetailes { get; set; }

    public virtual DbSet<tailorhand> tailorhands { get; set; }

    public virtual DbSet<tailorheader> tailorheaders { get; set; }

    public virtual DbSet<tailorjabzor> tailorjabzors { get; set; }

    public virtual DbSet<tailorneck> tailornecks { get; set; }

    public virtual DbSet<stok_transaction> stok_transaction { get; set; }

    public virtual DbSet<returned> returneds { get; set; }

    public virtual DbSet<returnedetaile> returnedetailes { get; set; }

    public virtual DbSet<UBL> UBLs { get; set; }

    public virtual DbSet<invtransaction> invtransactions { get; set; }


    public virtual int Getpaymentin()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Getpaymentin");
    }


    public virtual int Getpaymentout()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Getpaymentout");
    }


    public virtual int Getreturne()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Getreturne");
    }


    public virtual int Gettransactions()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Gettransactions");
    }

}

}

