
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Domain.Models
{

using System;
    using System.Collections.Generic;
    
public partial class exceptionpro
{

    public int Id { get; set; }

    public string Message { get; set; }

    public string StackTrace { get; set; }

    public string ClassName { get; set; }

    public string MethodName { get; set; }

    public string FileName { get; set; }

    public string LineNumber { get; set; }

    public string FormName { get; set; }

    public System.DateTime Date { get; set; }

}

}
