
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Domain.Models
{

using System;
    using System.Collections.Generic;
    
public partial class expens
{

    public int ID { get; set; }

    public string Description { get; set; }

    public Nullable<double> Amount { get; set; }

    public string CDate { get; set; }

    public Nullable<double> Vat { get; set; }

    public Nullable<int> Typeid { get; set; }

}

}
