
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Domain.Models
{

using System;
    using System.Collections.Generic;
    
public partial class invtransaction
{

    public int Id { get; set; }

    public string type { get; set; }

    public string Date { get; set; }

    public int Quantity { get; set; }

    public decimal Credit { get; set; }

    public decimal Dipt { get; set; }

    public int Proid { get; set; }

    public int transid { get; set; }

    public Nullable<int> Itemid { get; set; }

    public string Note { get; set; }

}

}
