
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Domain.Models
{

using System;
    using System.Collections.Generic;
    
public partial class item
{

    public int ID { get; set; }

    public string Itemname { get; set; }

    public double Itemprice { get; set; }

    public double Itemqty { get; set; }

    public int UID { get; set; }

    public int OpeningBalance { get; set; }

}

}
