
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Domain.Models
{

using System;
    using System.Collections.Generic;
    
public partial class itemsale
{

    public int ID { get; set; }

    public string Date { get; set; }

    public int Quantity { get; set; }

    public int Itemid { get; set; }

    public int invoiceno { get; set; }

}

}
