
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Domain.Models
{

using System;
    using System.Collections.Generic;
    
public partial class order
{

    public int Id { get; set; }

    public Nullable<int> Tailortype { get; set; }

    public Nullable<int> clothnational { get; set; }

    public Nullable<int> fabricid { get; set; }

    public Nullable<int> fabrictypeid { get; set; }

    public Nullable<decimal> fabriccount { get; set; }

    public Nullable<int> count { get; set; }

    public Nullable<int> empid { get; set; }

    public Nullable<int> ntid { get; set; }

    public Nullable<int> ntoid { get; set; }

    public Nullable<int> Receivedcount { get; set; }

    public Nullable<int> Remainingcount { get; set; }

    public string Status { get; set; }

}

}
