
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Domain.Models
{

using System;
    using System.Collections.Generic;
    
public partial class payment
{

    public int paymentNo { get; set; }

    public Nullable<int> InvoiceNo { get; set; }

    public Nullable<decimal> Cash { get; set; }

    public Nullable<decimal> Bank { get; set; }

    public Nullable<decimal> Paid { get; set; }

    public Nullable<decimal> Remaining { get; set; }

    public string Date { get; set; }

    public string Time { get; set; }

    public Nullable<int> ThirdPartyID { get; set; }

    public string PaymentMethod { get; set; }

    public string Type { get; set; }

    public string Note { get; set; }

}

}
