
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Domain.Models
{

using System;
    using System.Collections.Generic;
    
public partial class pricedetaile
{

    public int ID { get; set; }

    public Nullable<int> Priceid { get; set; }

    public Nullable<int> ProductNo { get; set; }

    public string TDDesc { get; set; }

    public Nullable<int> Unitid { get; set; }

    public Nullable<double> ItemPrice { get; set; }

    public Nullable<double> Quantity { get; set; }

    public Nullable<double> Subtotal { get; set; }

    public Nullable<double> Discount { get; set; }

    public Nullable<double> Totafterdiscount { get; set; }

    public Nullable<double> Total { get; set; }

}

}
