
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Domain.Models
{

using System;
    using System.Collections.Generic;
    
public partial class price
{

    public int ID { get; set; }

    public string Datefrom { get; set; }

    public string Dateto { get; set; }

    public Nullable<double> NonVatTotal { get; set; }

    public Nullable<double> Discount { get; set; }

    public Nullable<double> VatAmount { get; set; }

    public Nullable<double> TotalAmount { get; set; }

    public Nullable<int> ThirdPartyID { get; set; }

}

}
