
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Domain.Models
{

using System;
    using System.Collections.Generic;
    
public partial class product
{

    public int ProductNo { get; set; }

    public string ProductCode { get; set; }

    public string Description { get; set; }

    public string Barcode { get; set; }

    public decimal UnitPrice { get; set; }

    public int CategoryNo { get; set; }

    public Nullable<int> Unitid { get; set; }

    public Nullable<int> StocksOnHand { get; set; }

    public Nullable<bool> ShowInPOS { get; set; }

    public bool AllowInventory { get; set; }

    public Nullable<int> ReorderLevel { get; set; }

    public Nullable<int> Order { get; set; }

}

}
