
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Domain.Models
{

using System;
    using System.Collections.Generic;
    
public partial class returnedetaile
{

    public long TDetailNo { get; set; }

    public int InvoiceNo { get; set; }

    public long ProductNo { get; set; }

    public string TDDesc { get; set; }

    public Nullable<int> Unitid { get; set; }

    public double ItemPrice { get; set; }

    public double Quantity { get; set; }

    public double Subtotal { get; set; }

    public double Discount { get; set; }

    public Nullable<double> Totafterdiscount { get; set; }

    public Nullable<decimal> Total { get; set; }

}

}
