
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Domain.Models
{

using System;
    using System.Collections.Generic;
    
public partial class sale
{

    public int Invoiceno { get; set; }

    public string TDate { get; set; }

    public string TTime { get; set; }

    public double NonVatTotal { get; set; }

    public double Discount { get; set; }

    public double VatAmount { get; set; }

    public string TotalAmount { get; set; }

    public Nullable<int> ThirdPartyID { get; set; }

    public string Billtype { get; set; }

    public string Note { get; set; }

    public string Purchaseorder { get; set; }

    public string RN { get; set; }

    public string Proname { get; set; }

}

}
