
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Domain.Models
{

using System;
    using System.Collections.Generic;
    
public partial class staff
{

    public long StaffID { get; set; }

    public string Firstname { get; set; }

    public string Lastname { get; set; }

    public string Fullname { get; set; }

    public string Phonenumber { get; set; }

    public string Address { get; set; }

    public string Username { get; set; }

    public string UPassword { get; set; }

    public string Role { get; set; }

}

}
