
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Domain.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tailorjabzor
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tailorjabzor()
    {

        this.alltailorings = new HashSet<alltailoring>();

    }


    public string Id { get; set; }

    public Nullable<bool> Jab1 { get; set; }

    public Nullable<bool> Jab2 { get; set; }

    public Nullable<bool> Jab3 { get; set; }

    public Nullable<bool> Jab4 { get; set; }

    public Nullable<bool> Jab5 { get; set; }

    public Nullable<bool> Jab6 { get; set; }

    public Nullable<bool> Jab7 { get; set; }

    public Nullable<bool> Jab8 { get; set; }

    public Nullable<bool> Jab9 { get; set; }

    public Nullable<bool> Jab10 { get; set; }

    public Nullable<bool> Zigzag { get; set; }

    public Nullable<int> txtnumber { get; set; }

    public Nullable<decimal> txt { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<alltailoring> alltailorings { get; set; }

}

}
