
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Domain.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tailorbocket
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tailorbocket()
    {

        this.alltailorings = new HashSet<alltailoring>();

    }


    public string Id { get; set; }

    public Nullable<bool> Bok1 { get; set; }

    public Nullable<bool> Bok2 { get; set; }

    public Nullable<bool> Bok3 { get; set; }

    public Nullable<bool> Bok4 { get; set; }

    public Nullable<bool> Bok5 { get; set; }

    public Nullable<bool> Bok6 { get; set; }

    public Nullable<bool> Bok7 { get; set; }

    public Nullable<bool> Bok8 { get; set; }

    public Nullable<bool> Bok9 { get; set; }

    public Nullable<bool> Bok10 { get; set; }

    public Nullable<bool> Bok11 { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<alltailoring> alltailorings { get; set; }

}

}
