
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Domain.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tailorneck
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tailorneck()
    {

        this.alltailorings = new HashSet<alltailoring>();

    }


    public string Id { get; set; }

    public Nullable<bool> Plain { get; set; }

    public Nullable<bool> Plainfrench { get; set; }

    public Nullable<bool> Regulartipper { get; set; }

    public Nullable<bool> Closedflap { get; set; }

    public Nullable<bool> Plainhidden { get; set; }

    public Nullable<bool> Chinese { get; set; }

    public Nullable<bool> Openflap { get; set; }

    public Nullable<bool> Frenchflip { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<alltailoring> alltailorings { get; set; }

}

}
