
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Domain.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tailorheader
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tailorheader()
    {

        this.alltailorings = new HashSet<alltailoring>();

    }


    public string Id { get; set; }

    public Nullable<int> BTCNumber { get; set; }

    public int Custid { get; set; }

    public string Date { get; set; }

    public Nullable<int> Clothesnumber { get; set; }

    public Nullable<int> Clothesready { get; set; }

    public Nullable<int> Clothesrecived { get; set; }

    public Nullable<int> Clothesremining { get; set; }

    public Nullable<int> Total { get; set; }

    public Nullable<decimal> Paied { get; set; }

    public Nullable<decimal> Totalreimining { get; set; }

    public string Reciveddate { get; set; }

    public string Status { get; set; }

    public string Note { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<alltailoring> alltailorings { get; set; }

    public virtual thirdparty thirdparty { get; set; }

}

}
