
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Domain.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tailordetaile
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tailordetaile()
    {

        this.alltailorings = new HashSet<alltailoring>();

    }


    public string Id { get; set; }

    public string Frontlength { get; set; }

    public string Backlength { get; set; }

    public string Shoulder { get; set; }

    public string Handlength { get; set; }

    public string Neck { get; set; }

    public string Breadth { get; set; }

    public string Chest { get; set; }

    public string Handwidthabove { get; set; }

    public string Handwidthbelow { get; set; }

    public string Breadthbelow { get; set; }

    public string Handpalm { get; set; }

    public string Weight { get; set; }

    public string Notes { get; set; }

    public Nullable<bool> Aujra { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<alltailoring> alltailorings { get; set; }

}

}
