
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Domain.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tailorhand
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tailorhand()
    {

        this.alltailorings = new HashSet<alltailoring>();

    }


    public string Id { get; set; }

    public string Texta { get; set; }

    public string Taxtb { get; set; }

    public Nullable<bool> Inverted { get; set; }

    public Nullable<bool> Square { get; set; }

    public Nullable<bool> Horny { get; set; }

    public Nullable<bool> Round { get; set; }

    public Nullable<bool> Plain { get; set; }

    public Nullable<bool> Plain_cupcake { get; set; }

    public Nullable<bool> Triangle { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<alltailoring> alltailorings { get; set; }

}

}
