
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Domain.Models
{

using System;
    using System.Collections.Generic;
    
public partial class thirdparty
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public thirdparty()
    {

        this.tailorheaders = new HashSet<tailorheader>();

    }


    public int ID { get; set; }

    public string Name { get; set; }

    public string PhoneNumber { get; set; }

    public string MobileNumber { get; set; }

    public string Address { get; set; }

    public string City { get; set; }

    public string Comments { get; set; }

    public Nullable<int> Type { get; set; }

    public string Email { get; set; }

    public Nullable<double> OpeningBalance { get; set; }

    public string Taxnumber { get; set; }

    public string CRN { get; set; }

    public string Billnumber { get; set; }

    public string Pagenumber { get; set; }

    public string StreetName { get; set; }

    public string BuildingNumber { get; set; }

    public string CitySubdivisionName { get; set; }

    public string CityName { get; set; }

    public string PostalZone { get; set; }

    public Nullable<bool> ISUsePhase2 { get; set; }

    public Nullable<int> Kafid { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tailorheader> tailorheaders { get; set; }

    public virtual Kafil Kafil { get; set; }

}

}
