
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Domain.Models
{

using System;
    using System.Collections.Generic;
    
public partial class transaction
{

    public int ID { get; set; }

    public Nullable<int> Invoiceno { get; set; }

    public Nullable<int> Paynum { get; set; }

    public string TDate { get; set; }

    public string Type { get; set; }

    public Nullable<int> ThirdPartyID { get; set; }

    public Nullable<decimal> Paid { get; set; }

    public string Paytype { get; set; }

    public string Note { get; set; }

}

}
