
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Domain.Models
{

using System;
    using System.Collections.Generic;
    
public partial class UBL
{

    public int Id { get; set; }

    public string QRCode { get; set; }

    public string Invoicehash { get; set; }

    public string Uuid { get; set; }

    public string Invoice { get; set; }

    public Nullable<int> Saleid { get; set; }

    public string Status { get; set; }

    public string Path { get; set; }

    public int invoicenumber { get; set; }

    public string PIH { get; set; }

    public string Flage { get; set; }

}

}
