
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Domain.Models
{

using System;
    using System.Collections.Generic;
    
public partial class voucher
{

    public int Id { get; set; }

    public Nullable<int> Billnumber { get; set; }

    public Nullable<int> Thiredpartyid { get; set; }

    public string Date { get; set; }

    public string Vochertypes { get; set; }

    public Nullable<decimal> Paid { get; set; }

    public string Paymentmathod { get; set; }

    public string Note { get; set; }

    public string Methode { get; set; }

    public string Billnum { get; set; }

}

}
